/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meusapps_backend.view;

import javax.swing.JTabbedPane;

/**
 *
 * @author pontejunior
 */
public class JFramePrincipal extends javax.swing.JFrame {

    JPanelClientes jPanelClientes = new JPanelClientes();
    JInternalFrameClientes jInternalFrameClientes = new JInternalFrameClientes();
    JInternalFrameFornecedores jInternalFrameFornecedores = new JInternalFrameFornecedores();
    
    
    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButtonClientes = new javax.swing.JButton();
        jButtonFornecedores = new javax.swing.JButton();
        jButtonProdutos = new javax.swing.JButton();
        jButtonPedidosDeCompras = new javax.swing.JButton();
        jButtonDevoluções = new javax.swing.JButton();
        jButtonOrçamentos = new javax.swing.JButton();
        jButtonPedidosDeFaturamento = new javax.swing.JButton();
        jButtonPedidosDeVenda = new javax.swing.JButton();
        jButtonPreVendas = new javax.swing.JButton();
        jButtonNotaFiscalDeEntrada = new javax.swing.JButton();
        jButtonNotaFiscalDeSaída = new javax.swing.JButton();
        jButtonCaixa = new javax.swing.JButton();
        jButtonBancos = new javax.swing.JButton();
        jButtonContasAPagar = new javax.swing.JButton();
        jButtonContasAReceber = new javax.swing.JButton();
        jButtonNavegaçãoRápida = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuItemCompradores = new javax.swing.JMenuItem();
        jMenuItemEntregadores = new javax.swing.JMenuItem();
        jMenuItemFabricantes = new javax.swing.JMenuItem();
        jMenuItemFornecedores = new javax.swing.JMenuItem();
        jMenuItemGarcom = new javax.swing.JMenuItem();
        jMenuItemMotoristas = new javax.swing.JMenuItem();
        jMenuItemPortadores = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuCompras = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuFinanceiro = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 721));
        setSize(1024, 768);

        jButtonClientes.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jButtonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logoeaofazul.jpg"))); // NOI18N
        jButtonClientes.setText("Clientes");
        jButtonClientes.setAlignmentY(0.0F);
        jButtonClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClientes.setNextFocusableComponent(jButtonFornecedores);
        jButtonClientes.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });

        jButtonFornecedores.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jButtonFornecedores.setText("Fornecedores");
        jButtonFornecedores.setAlignmentY(0.0F);
        jButtonFornecedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFornecedores.setNextFocusableComponent(jButtonFornecedores);
        jButtonFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFornecedoresActionPerformed(evt);
            }
        });

        jButtonProdutos.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jButtonProdutos.setText("Produtos");
        jButtonProdutos.setAlignmentY(0.0F);
        jButtonProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonProdutos.setNextFocusableComponent(jButtonFornecedores);
        jButtonProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProdutosActionPerformed(evt);
            }
        });

        jButtonPedidosDeCompras.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jButtonPedidosDeCompras.setText("Pedidos de Compra");
        jButtonPedidosDeCompras.setAlignmentY(0.0F);
        jButtonPedidosDeCompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPedidosDeCompras.setNextFocusableComponent(jButtonFornecedores);
        jButtonPedidosDeCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPedidosDeComprasActionPerformed(evt);
            }
        });

        jButtonDevoluções.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jButtonDevoluções.setText("Devoluções");
        jButtonDevoluções.setAlignmentY(0.0F);
        jButtonDevoluções.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDevoluções.setNextFocusableComponent(jButtonFornecedores);
        jButtonDevoluções.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevoluçõesActionPerformed(evt);
            }
        });

        jButtonOrçamentos.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jButtonOrçamentos.setText("Orçamentos");
        jButtonOrçamentos.setAlignmentY(0.0F);
        jButtonOrçamentos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonOrçamentos.setNextFocusableComponent(jButtonFornecedores);
        jButtonOrçamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrçamentosActionPerformed(evt);
            }
        });

        jButtonPedidosDeFaturamento.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jButtonPedidosDeFaturamento.setText("Pedidos de faturamento");
        jButtonPedidosDeFaturamento.setAlignmentY(0.0F);
        jButtonPedidosDeFaturamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPedidosDeFaturamento.setNextFocusableComponent(jButtonFornecedores);
        jButtonPedidosDeFaturamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPedidosDeFaturamentoActionPerformed(evt);
            }
        });

        jButtonPedidosDeVenda.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jButtonPedidosDeVenda.setText("Pedidos de venda");
        jButtonPedidosDeVenda.setAlignmentY(0.0F);
        jButtonPedidosDeVenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPedidosDeVenda.setNextFocusableComponent(jButtonFornecedores);
        jButtonPedidosDeVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPedidosDeVendaActionPerformed(evt);
            }
        });

        jButtonPreVendas.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jButtonPreVendas.setText("Pré-vendas");
        jButtonPreVendas.setAlignmentY(0.0F);
        jButtonPreVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPreVendas.setNextFocusableComponent(jButtonFornecedores);
        jButtonPreVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreVendasActionPerformed(evt);
            }
        });

        jButtonNotaFiscalDeEntrada.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jButtonNotaFiscalDeEntrada.setText("Nota fiscal de entrada");
        jButtonNotaFiscalDeEntrada.setAlignmentY(0.0F);
        jButtonNotaFiscalDeEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNotaFiscalDeEntrada.setNextFocusableComponent(jButtonFornecedores);
        jButtonNotaFiscalDeEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNotaFiscalDeEntradaActionPerformed(evt);
            }
        });

        jButtonNotaFiscalDeSaída.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jButtonNotaFiscalDeSaída.setText("Nota fiscal de saída");
        jButtonNotaFiscalDeSaída.setAlignmentY(0.0F);
        jButtonNotaFiscalDeSaída.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNotaFiscalDeSaída.setNextFocusableComponent(jButtonFornecedores);
        jButtonNotaFiscalDeSaída.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNotaFiscalDeSaídaActionPerformed(evt);
            }
        });

        jButtonCaixa.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jButtonCaixa.setText("Caixa");
        jButtonCaixa.setAlignmentY(0.0F);
        jButtonCaixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCaixa.setNextFocusableComponent(jButtonFornecedores);
        jButtonCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCaixaActionPerformed(evt);
            }
        });

        jButtonBancos.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jButtonBancos.setText("Bancos");
        jButtonBancos.setAlignmentY(0.0F);
        jButtonBancos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBancos.setNextFocusableComponent(jButtonFornecedores);
        jButtonBancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBancosActionPerformed(evt);
            }
        });

        jButtonContasAPagar.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jButtonContasAPagar.setText("Contas a pagar");
        jButtonContasAPagar.setAlignmentY(0.0F);
        jButtonContasAPagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonContasAPagar.setNextFocusableComponent(jButtonFornecedores);
        jButtonContasAPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContasAPagarActionPerformed(evt);
            }
        });

        jButtonContasAReceber.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jButtonContasAReceber.setText("Contas a receber");
        jButtonContasAReceber.setAlignmentY(0.0F);
        jButtonContasAReceber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonContasAReceber.setNextFocusableComponent(jButtonFornecedores);
        jButtonContasAReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContasAReceberActionPerformed(evt);
            }
        });

        jButtonNavegaçãoRápida.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jButtonNavegaçãoRápida.setText("Navegação rápida");
        jButtonNavegaçãoRápida.setAlignmentY(0.0F);
        jButtonNavegaçãoRápida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNavegaçãoRápida.setNextFocusableComponent(jButtonFornecedores);
        jButtonNavegaçãoRápida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNavegaçãoRápidaActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jButtonClientes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButtonFornecedores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButtonProdutos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButtonPedidosDeCompras, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButtonDevoluções, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButtonOrçamentos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButtonPedidosDeFaturamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButtonPedidosDeVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButtonPreVendas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButtonNotaFiscalDeEntrada, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButtonNotaFiscalDeSaída, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButtonCaixa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButtonBancos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButtonContasAPagar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButtonContasAReceber, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButtonNavegaçãoRápida, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFornecedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPedidosDeCompras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDevoluções)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOrçamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPedidosDeFaturamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPedidosDeVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPreVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNotaFiscalDeEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNotaFiscalDeSaída)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBancos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonContasAPagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonContasAReceber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNavegaçãoRápida)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNavegaçãoRápida, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonContasAReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonContasAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonBancos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonNotaFiscalDeSaída, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonNotaFiscalDeEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonPreVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonPedidosDeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonPedidosDeFaturamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonOrçamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonDevoluções, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonPedidosDeCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonClientes))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 204));
        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(204, 255, 204), new java.awt.Color(255, 255, 204), new java.awt.Color(153, 153, 255)));
        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(800, 600));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentHidden(evt);
            }
        });

        jMenuCadastro.setText("Cadastros");

        jMenuItemClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemClientes.setText("Clientes");
        jMenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientesActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemClientes);

        jMenuItemCompradores.setText("Compradores");
        jMenuCadastro.add(jMenuItemCompradores);

        jMenuItemEntregadores.setText("Entregadores");
        jMenuCadastro.add(jMenuItemEntregadores);

        jMenuItemFabricantes.setText("Fabricantes");
        jMenuCadastro.add(jMenuItemFabricantes);

        jMenuItemFornecedores.setText("Fornecedores");
        jMenuItemFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFornecedoresActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemFornecedores);

        jMenuItemGarcom.setText("Garçom");
        jMenuCadastro.add(jMenuItemGarcom);

        jMenuItemMotoristas.setText("Motoristas");
        jMenuCadastro.add(jMenuItemMotoristas);

        jMenuItemPortadores.setText("Portadores");
        jMenuCadastro.add(jMenuItemPortadores);

        jMenuItem9.setText("Produtos");
        jMenuCadastro.add(jMenuItem9);

        jMenuItem10.setText("Serviços");
        jMenuCadastro.add(jMenuItem10);

        jMenuItem11.setText("Transportadoras");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItem11);

        jMenuItem12.setText("Técnicos");
        jMenuCadastro.add(jMenuItem12);

        jMenuItem13.setText("Outros");
        jMenuCadastro.add(jMenuItem13);

        jMenuItem14.setText("Relatórios");
        jMenuCadastro.add(jMenuItem14);
        jMenuCadastro.add(jSeparator1);

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemSair);

        jMenuBar1.add(jMenuCadastro);

        jMenuCompras.setText("Compras");
        jMenuBar1.add(jMenuCompras);

        jMenu3.setText("Produção");
        jMenuBar1.add(jMenu3);

        jMenu2.setText("Vendas");
        jMenuBar1.add(jMenu2);

        jMenu5.setText("Ordem de Serviço");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Notas Fiscais");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Contabilidade");
        jMenuBar1.add(jMenu7);

        jMenu8.setText("CRM");
        jMenuBar1.add(jMenu8);

        jMenu9.setText("Estoque");
        jMenuBar1.add(jMenu9);

        jMenuFinanceiro.setText("Financeiro");
        jMenuBar1.add(jMenuFinanceiro);

        jMenu11.setText("Ferramentas");
        jMenuBar1.add(jMenu11);

        jMenu12.setText("Concentrador");
        jMenuBar1.add(jMenu12);

        jMenu13.setText("Ajuda");
        jMenuBar1.add(jMenu13);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        // TODO add your handling code here:
        /*Component componentes [] = jTabbedPane1.getComponents();
        boolean achou = false;
        for(int i=0; i< componentes.length; i++){
            if(componentes[i].getClass().isInstance(JPanelClientes.class)){
                achou = true;
            }
        }
        */
        //if(!achou)
            //jInternalFrameClientes.add(jPanelClientes);
            
            jTabbedPane1.addTab("Clientes",jInternalFrameClientes);
            jInternalFrameClientes.show();
            //jInternalFrameClientes.setVisible(true);
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonBancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBancosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBancosActionPerformed

    private void jButtonOrçamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrçamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOrçamentosActionPerformed

    private void jButtonDevoluçõesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevoluçõesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDevoluçõesActionPerformed

    private void jButtonPedidosDeComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPedidosDeComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPedidosDeComprasActionPerformed

    private void jButtonProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProdutosActionPerformed

    private void jButtonFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFornecedoresActionPerformed
        // TODO add your handling code here:
            jTabbedPane1.addTab("Fornecedores",jInternalFrameFornecedores);
            jInternalFrameFornecedores.show();
            //jInternalFrameFornecedores.setVisible(true);
    }//GEN-LAST:event_jButtonFornecedoresActionPerformed

    private void jButtonNavegaçãoRápidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNavegaçãoRápidaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonNavegaçãoRápidaActionPerformed

    private void jButtonContasAReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContasAReceberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonContasAReceberActionPerformed

    private void jButtonContasAPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContasAPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonContasAPagarActionPerformed

    private void jButtonCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCaixaActionPerformed

    private void jButtonNotaFiscalDeSaídaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNotaFiscalDeSaídaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNotaFiscalDeSaídaActionPerformed

    private void jButtonNotaFiscalDeEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNotaFiscalDeEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNotaFiscalDeEntradaActionPerformed

    private void jButtonPreVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPreVendasActionPerformed

    private void jButtonPedidosDeVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPedidosDeVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPedidosDeVendaActionPerformed

    private void jButtonPedidosDeFaturamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPedidosDeFaturamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPedidosDeFaturamentoActionPerformed

    private void jMenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientesActionPerformed
        
        // TODO add your handling code here:
        //jTabbedPane1.add(jPanelClientes);
            //jPanelClientes.add(jInternalFrameClientes);
            //jTabbedPane1.addTab("Clientes",jPanelClientes);
            
            //jInternalFrameClientes.add(jPanelClientes);
            //jInternalFrameClientes.show();
            jTabbedPane1.addTab("Clientes",jInternalFrameClientes);
            jInternalFrameClientes.show();
            //jInternalFrameClientes.setVisible(true);
    }//GEN-LAST:event_jMenuItemClientesActionPerformed

    private void jMenuItemFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFornecedoresActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.addTab("Fornecedores", jInternalFrameFornecedores);
        jInternalFrameFornecedores.show();
        //jInternalFrameFornecedores.setVisible(true);
    }//GEN-LAST:event_jMenuItemFornecedoresActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        //exit(0);
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jTabbedPane1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1ComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBancos;
    private javax.swing.JButton jButtonCaixa;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonContasAPagar;
    private javax.swing.JButton jButtonContasAReceber;
    private javax.swing.JButton jButtonDevoluções;
    private javax.swing.JButton jButtonFornecedores;
    private javax.swing.JButton jButtonNavegaçãoRápida;
    private javax.swing.JButton jButtonNotaFiscalDeEntrada;
    private javax.swing.JButton jButtonNotaFiscalDeSaída;
    private javax.swing.JButton jButtonOrçamentos;
    private javax.swing.JButton jButtonPedidosDeCompras;
    private javax.swing.JButton jButtonPedidosDeFaturamento;
    private javax.swing.JButton jButtonPedidosDeVenda;
    private javax.swing.JButton jButtonPreVendas;
    private javax.swing.JButton jButtonProdutos;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuCompras;
    private javax.swing.JMenu jMenuFinanceiro;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemCompradores;
    private javax.swing.JMenuItem jMenuItemEntregadores;
    private javax.swing.JMenuItem jMenuItemFabricantes;
    private javax.swing.JMenuItem jMenuItemFornecedores;
    private javax.swing.JMenuItem jMenuItemGarcom;
    private javax.swing.JMenuItem jMenuItemMotoristas;
    private javax.swing.JMenuItem jMenuItemPortadores;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public static javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
